# Generated by Django 5.2.12 on 2026-03-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorDomainTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(help_text='域名', max_length=255, unique=True, verbose_name='域名')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('priority', models.SmallIntegerField(default=0, help_text='优先级', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('last_scheduled_at', models.DateTimeField(blank=True, help_text='最后调度时间', null=True, verbose_name='最后调度时间')),
                ('schedule_interval_minutes', models.IntegerField(default=10, help_text='调度间隔分钟', verbose_name='调度间隔分钟')),
            ],
            options={
                'verbose_name': '监控目标域名',
                'verbose_name_plural': '监控目标域名',
                'db_table': 'monitor_domain_targets',
            },
        ),
        migrations.CreateModel(
            name='MonitorPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(help_text='模拟测试平台', max_length=255, unique=True, verbose_name='模拟测试平台')),
                ('enabled', models.BooleanField(default=False, help_text='是否启用', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模拟测试平台',
                'verbose_name_plural': '模拟测试平台',
                'db_table': 'monitor_platforms',
            },
        ),
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(help_text='域名', max_length=255, verbose_name='域名')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('unknow', 'unknow'), ('running', 'running')], help_text='状态，可选：success, failed, unknow, running', max_length=10, verbose_name='状态')),
                ('proxy_ip', models.TextField(help_text='代理服务器ip', verbose_name='代理服务器ip')),
                ('headless', models.BooleanField(default=False, help_text='是否启用浏览器 headless 模式', verbose_name='浏览器 headless 模式')),
                ('count', models.IntegerField(default=0, help_text='抓取结果数', verbose_name='抓取结果数')),
                ('browser_launch_ms', models.FloatField(blank=True, help_text='浏览器启动时间', null=True, verbose_name='浏览器启动时间')),
                ('collect_ms', models.FloatField(blank=True, help_text='数据采集时间', null=True, verbose_name='数据采集时间')),
                ('insert_ms', models.FloatField(blank=True, help_text='数据插入时间', null=True, verbose_name='数据插入时间')),
                ('total_ms', models.FloatField(blank=True, help_text='总时间', null=True, verbose_name='总时间')),
                ('error_type', models.TextField(blank=True, help_text='错误类型', null=True, verbose_name='错误类型')),
                ('error_message', models.TextField(blank=True, help_text='错误信息', null=True, verbose_name='错误信息')),
                ('platform', models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='monitor.monitorplatform')),
            ],
            options={
                'verbose_name': '监控任务',
                'verbose_name_plural': '监控任务',
                'db_table': 'monitor_tasks',
            },
        ),
        migrations.CreateModel(
            name='MonitorDomainResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp', models.TextField(blank=True, help_text='IP 所属运营商', null=True, verbose_name='IP 所属运营商')),
                ('region', models.TextField(blank=True, help_text='地区', null=True, verbose_name='地区')),
                ('download_time', models.FloatField(blank=True, help_text='下载时间', null=True, verbose_name='下载时间')),
                ('connect_time', models.FloatField(blank=True, help_text='连接时间', null=True, verbose_name='连接时间')),
                ('dns_time', models.FloatField(blank=True, help_text='DNS 解析时间', null=True, verbose_name='DNS 解析时间')),
                ('total_time', models.FloatField(blank=True, help_text='数据抓取总时间', null=True, verbose_name='数据抓取总时间')),
                ('status_code', models.TextField(blank=True, help_text='检测状态码', null=True, verbose_name='检测状态码')),
                ('ip_location', models.TextField(blank=True, help_text='响应 IP 位置', null=True, verbose_name='响应 IP 位置')),
                ('response_ip', models.TextField(blank=True, help_text='响应 IP', null=True, verbose_name='响应 IP')),
                ('raw', models.JSONField(blank=True, help_text='原始数据', null=True, verbose_name='原始数据')),
                ('ip_country', models.TextField(blank=True, help_text='IP 所属国家', null=True, verbose_name='IP 所属国家')),
                ('ip_province', models.TextField(blank=True, help_text='IP 所属省份', null=True, verbose_name='IP 所属省份')),
                ('ip_city', models.TextField(blank=True, help_text='IP 所属城市', null=True, verbose_name='IP 所属城市')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitor.monitortask')),
            ],
            options={
                'verbose_name': '域名检测结果',
                'verbose_name_plural': '域名检测结果',
                'db_table': 'monitor_results',
            },
        ),
        migrations.CreateModel(
            name='MonitorWaitingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(help_text='域名', max_length=255, verbose_name='域名')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('failed', 'failed'), ('success', 'success'), ('unknow', 'unknow')], default='waiting', help_text='状态，可选：running, failed, success, unknow', max_length=10, verbose_name='状态')),
                ('lease_until', models.DateTimeField(blank=True, help_text='租约过期时间', null=True, verbose_name='租约过期时间')),
                ('worker_id', models.TextField(blank=True, help_text='worker ID', null=True, verbose_name='worker ID')),
                ('attempts', models.IntegerField(default=0, help_text='尝试次数', verbose_name='尝试次数')),
                ('error_message', models.TextField(blank=True, help_text='错误信息', null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('target', models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.CASCADE, related_name='waiting_tasks', to='monitor.monitordomaintarget')),
            ],
            options={
                'verbose_name': '监控等待任务队列',
                'verbose_name_plural': '监控等待任务队列',
                'db_table': 'monitor_waiting_tasks',
                'indexes': [models.Index(fields=['created_at'], name='idx_waiting_tasks_created'), models.Index(fields=['status', 'lease_until'], name='idx_waiting_tasks_status_lease'), models.Index(fields=['target'], name='idx_waiting_tasks_target'), models.Index(fields=['updated_at'], name='idx_waiting_tasks_updated')],
            },
        ),
    ]
