# Generated by Django 5.2.12 on 2026-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitordomainresult',
            name='ip_city',
        ),
        migrations.RemoveField(
            model_name='monitordomainresult',
            name='ip_country',
        ),
        migrations.RemoveField(
            model_name='monitordomainresult',
            name='ip_province',
        ),
        migrations.RemoveField(
            model_name='monitordomainresult',
            name='region',
        ),
        migrations.AddField(
            model_name='monitordomainresult',
            name='detect_node_location',
            field=models.TextField(blank=True, help_text='检测节点位置', null=True, verbose_name='检测节点位置'),
        ),
        migrations.AddField(
            model_name='monitordomainresult',
            name='domain',
            field=models.TextField(default='', help_text='检测域名', max_length=255, verbose_name='检测域名'),
        ),
        migrations.AddField(
            model_name='monitordomainresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
