# Generated by Django 5.2.12 on 2026-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_monitordomainresult_ip_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorplatform',
            name='website_url',
            field=models.TextField(default='', help_text='模拟测试平台入口', verbose_name='模拟测试平台入口'),
        ),
    ]
