# Generated by Django 5.2.12 on 2026-03-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorplatform_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置键', max_length=128, unique=True, verbose_name='配置键')),
                ('value_type', models.CharField(choices=[('bool', 'bool'), ('int', 'int'), ('float', 'float'), ('str', 'str'), ('json', 'json')], default='str', help_text='值类型', max_length=8, verbose_name='值类型')),
                ('value_str', models.TextField(blank=True, null=True, verbose_name='字符串值')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='整数值')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='浮点值')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='JSON 值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监控 APP 配置项',
                'verbose_name_plural': '监控 APP 配置项',
                'db_table': 'monitor_config',
                'indexes': [models.Index(fields=['key'], name='ix_mcfg_key')],
            },
        ),
    ]
