# Generated by Django 5.2.12 on 2026-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorconfig',
            name='value_str',
            field=models.CharField(blank=True, null=True, verbose_name='字符串值'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='detect_node_location',
            field=models.CharField(blank=True, help_text='检测节点位置', null=True, verbose_name='检测节点位置'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='domain',
            field=models.CharField(default='', help_text='检测域名', max_length=255, verbose_name='检测域名'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='ip_location',
            field=models.CharField(blank=True, help_text='响应 IP 位置', null=True, verbose_name='响应 IP 位置'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='isp',
            field=models.CharField(blank=True, help_text='IP 所属运营商', null=True, verbose_name='IP 所属运营商'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='response_ip',
            field=models.CharField(blank=True, help_text='响应 IP', null=True, verbose_name='响应 IP'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='status_code',
            field=models.CharField(blank=True, help_text='检测状态码', null=True, verbose_name='检测状态码'),
        ),
        migrations.AlterField(
            model_name='monitordomaintarget',
            name='domain',
            field=models.CharField(help_text='域名', max_length=255, unique=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='monitorplatform',
            name='platform',
            field=models.CharField(help_text='模拟测试平台', max_length=255, unique=True, verbose_name='模拟测试平台'),
        ),
        migrations.AlterField(
            model_name='monitorplatform',
            name='website_url',
            field=models.CharField(default='', help_text='模拟测试平台入口', verbose_name='模拟测试平台入口'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='domain',
            field=models.CharField(help_text='域名', max_length=255, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='proxy_ip',
            field=models.CharField(help_text='代理服务器ip', verbose_name='代理服务器ip'),
        ),
        migrations.AlterField(
            model_name='monitorwaitingtask',
            name='domain',
            field=models.CharField(help_text='域名', max_length=255, verbose_name='域名'),
        ),
    ]
