# Generated by Django 5.2.12 on 2026-03-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_monitorconfig_value_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='error_type',
            field=models.CharField(blank=True, help_text='错误类型', null=True, verbose_name='错误类型'),
        ),
        migrations.AlterField(
            model_name='monitorwaitingtask',
            name='worker_id',
            field=models.CharField(blank=True, help_text='worker ID', null=True, verbose_name='worker ID'),
        ),
    ]
