# Generated by Django 5.2.12 on 2026-03-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_monitortask_error_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorconfig',
            name='value_bool',
            field=models.BooleanField(blank=True, help_text='布尔值', null=True, verbose_name='布尔值'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='value_float',
            field=models.FloatField(blank=True, help_text='浮点值', null=True, verbose_name='浮点值'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='value_int',
            field=models.IntegerField(blank=True, help_text='整数值', null=True, verbose_name='整数值'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='value_json',
            field=models.JSONField(blank=True, help_text='JSON 值', null=True, verbose_name='JSON 值'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='value_str',
            field=models.CharField(blank=True, help_text='字符串值', max_length=255, null=True, verbose_name='字符串值'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='detect_node_location',
            field=models.CharField(blank=True, help_text='检测节点位置', max_length=255, null=True, verbose_name='检测节点位置'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='ip_location',
            field=models.CharField(blank=True, help_text='响应 IP 位置', max_length=255, null=True, verbose_name='响应 IP 位置'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='isp',
            field=models.CharField(blank=True, help_text='IP 所属运营商', max_length=255, null=True, verbose_name='IP 所属运营商'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='response_ip',
            field=models.CharField(blank=True, help_text='响应 IP', max_length=255, null=True, verbose_name='响应 IP'),
        ),
        migrations.AlterField(
            model_name='monitordomainresult',
            name='status_code',
            field=models.CharField(blank=True, help_text='检测状态码', max_length=255, null=True, verbose_name='检测状态码'),
        ),
        migrations.AlterField(
            model_name='monitorplatform',
            name='website_url',
            field=models.CharField(default='', help_text='模拟测试平台入口', max_length=2048, verbose_name='模拟测试平台入口'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='error_type',
            field=models.CharField(blank=True, help_text='错误类型', max_length=255, null=True, verbose_name='错误类型'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='proxy_ip',
            field=models.CharField(help_text='代理服务器ip', max_length=255, verbose_name='代理服务器ip'),
        ),
        migrations.AlterField(
            model_name='monitorwaitingtask',
            name='worker_id',
            field=models.CharField(blank=True, help_text='worker ID', max_length=255, null=True, verbose_name='worker ID'),
        ),
    ]
