# Generated by Django 5.2.12 on 2026-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_monitorconfig_value_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='failure_rate',
            field=models.FloatField(blank=True, default=0.0, help_text='此次任务采集数据中，访问失败的比例（0~1）', null=True, verbose_name='域名访问失败率'),
        ),
    ]
