# Generated by Django 5.2.12 on 2026-04-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_monitortask_failure_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAlertedDomais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', help_text='告警域名', max_length=255, verbose_name='告警域名')),
                ('alert_time', models.DateTimeField(auto_now_add=True, help_text='告警时间', verbose_name='告警时间')),
                ('alert_type', models.CharField(blank=True, help_text='告警类型', max_length=255, null=True, verbose_name='告警类型')),
                ('alert_message', models.TextField(blank=True, help_text='告警信息', null=True, verbose_name='告警信息')),
            ],
            options={
                'verbose_name': '告警域名',
                'verbose_name_plural': '告警域名',
            },
        ),
    ]
