services:
  db:
    image: postgres:15-alpine
    environment:
      - TZ=Asia/Shanghai
    ports:
      - ${POSTGRES_DB_LISTEN_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  django-server:
    build: .
    init: true      # 僵尸进程回收
    environment:
      - TZ=Asia/Shanghai
    ports:
      - ${DJANGO_SERVER_PORT}:${DJANGO_SERVER_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py runserver 0.0.0.0:${DJANGO_SERVER_PORT}

  monitor-producer:
    build: .
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py producer

  monitor-worker1:
    build: .
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker

  monitor-worker2:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker

  monitor-worker3:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker    

  monitor-worker4:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker        

  monitor-worker5:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker

  monitor-worker6:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker

  monitor-worker7:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker

  monitor-worker8:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker    

  monitor-worker9:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker    

  monitor-worker10:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker

  monitor-worker11:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker    

  monitor-worker12:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker      

  monitor-worker13:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker  
  monitor-worker14:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker      

  monitor-worker15:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker  

  monitor-worker16:
    image: vp-monitor-monitor-worker1:latest
    init: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    env_file:
      - .env
    command: python devops_django_server/manage.py worker      