# Generated by Django 5.2.12 on 2026-03-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_vendor_name_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAPIAuthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='账号名称')),
                ('sub_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='子账号')),
                ('email', models.EmailField(blank=True, help_text='账号邮箱', max_length=254, null=True, verbose_name='账号邮箱')),
                ('api_key', models.TextField(blank=True, help_text='API Key, access key', null=True, verbose_name='API Key')),
                ('api_secret', models.TextField(blank=True, help_text='API Secret, secret key', null=True, verbose_name='API Secret')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', help_text='API 状态', max_length=16, verbose_name='API 状态')),
                ('status_info', models.CharField(blank=True, help_text='API 状态信息', max_length=1024, null=True, verbose_name='API 状态信息')),
                ('description', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vendor', models.ForeignKey(help_text='供应商', on_delete=django.db.models.deletion.PROTECT, related_name='auth_keys', to='config.vendor', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '云 API 认证密钥',
                'verbose_name_plural': '云 API 认证密钥',
                'db_table': 'cloud_api_auth_key',
                'indexes': [models.Index(fields=['vendor', 'status'], name='ix_caak_vendor_status')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'name'), name='uq_caak_vendor_name')],
            },
        ),
    ]
