# Generated by Django 5.2.12 on 2026-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_cloudapiauthkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='供应商描述'),
        ),
    ]
