# Generated by Django 5.2.12 on 2026-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_vendor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudapiauthkey',
            name='api_key_1',
            field=models.TextField(blank=True, help_text='API Key 1, access key 1', null=True, verbose_name='API Key 1'),
        ),
        migrations.AddField(
            model_name='cloudapiauthkey',
            name='api_secret_1',
            field=models.TextField(blank=True, help_text='API Secret 1, secret key 1', null=True, verbose_name='API Secret 1'),
        ),
    ]
